config/routes.rb
Pr::Application.routes.draw do
  resources :advertisements
  root to: "static_pages#home"

  get "contacts/index"

  get "dashboards/index"

  get "feeds/post"

  get "comments/create"
  get "comments/like"
  get "comments/delete"

  post "endorsements/create"

  delete 'endorsements/destroy', to: 'endorsements#destroy'

  get "friends/delete"

  get "searches/results"

  get "recommendations/suggestions"

  get "casinos/index"
  get "casinos/:id", to: "casinos#show", as: 'casino'
  post "casinos/recommend"

  get "online_sites/index"
  get "online_sites/:id", to: "online_sites#show"
  post "online_sites/recommend"

  get "user_plans/new"
  get "user_plans/edit"
  get 'user_plans/no_subscription', to: 'user_plans#no_subscription', as: 'no_subscription'
  get 'user_plans/upgrade'
  get 'user_plans/update'
  get 'user_plans/history'
  get 'user_plans/subscribed'
  post "user_plans/create"

   mount RailsAdmin::Engine => "/O2cq8T1Tj28xW2", :as => 'rails_admin' 
   # do   
  #    get "users/:prid", to: "users#show"

  #  end

  get "home", to: "static_pages#home"
  get "is_subscibed", to: "static_pages#is_subscibed"
  match "/contact", to: "static_pages#contact", as: 'contact_us',via: [:get]
  match "/privacy_policy", to: "static_pages#privacy_policy", as: 'privacy_policy',via: [:get]
  match "/about_us", to: "static_pages#about_us", as: 'about_us',via: [:get]
  get "static_pages/disclaimer"
  match "/user_agreement", to: "static_pages#user_agreement", as: 'user_agreement',via: [:get]
  get "static_pages/careers"
  post 'static_pages/send_email', to: 'static_pages#send_contact_email'

  get "password_resets/new"
  post "password_resets/create"

  get "users/new"

  post "users/create"
  delete 'signout', to: 'user_sessions#destroy'

  get "users/edit"
  get "users/confirm"
  get "users/request_confirm_code"
  patch "users/update"

  # Posts
  get 'posts/index', to: 'posts#index', as: 'posts'
  post 'posts/create', to: 'posts#create'
  post 'posts/like', to: 'posts#like'
  get 'posts/user_lists', to: 'posts#user_lists'
  # Comments
  post 'comments/create', to: 'comments#create'


  # Experiences
  get 'users/experiences/autocomplete', to: 'experiences#autocomplete'
  get 'users/experience/edit', to: 'experiences#edit'
  post "users/experience/create", to: "experiences#create"
  patch 'users/experiences/update', to: 'experiences#update', as: 'experience'
  delete 'users/experiences/destroy', to: 'experiences#destroy'


  # Achievements
  get 'users/achievements/edit', to: 'achievements#edit'
  post "users/achievements/create", to: "achievements#create"
  patch 'users/achievements/update', to: 'achievements#update', as: 'achievement'
  delete 'users/achievements/destroy', to: 'achievements#destroy'


  # Recommendations
  get 'users/recommendations/edit', to: 'recommendations#edit'
  post 'users/recommendations/create', to: 'recommendations#create'
  patch 'users/recommendations/update', to: 'recommendations#update', as: 'recommendation'
  delete 'users/recommendations/destroy', to: 'recommendations#destroy'


  # Endorsements
  post 'users/endorsements/create', to: 'endorsements#create'


  # Mailbox
  get "users/inbox", to: "user_messages#index", as: "user_messages"
  get "users/sent", to: "user_messages#sent", as: "user_messages_sent"
  get "users/trash", to: "user_messages#trash", as: "user_messages_trash"
  get "users/inbox/new", to: "user_messages#new", as: "new_message"
  get "users/inbox/:id", to: "user_messages#show", as: "user_messages_show"

  # Profile
   get "/:prid", to: "users#show", as: "profile"
  get "users/:prid/edit_profile", to: 'users#edit_profile', as: 'edit_profile'

  post "users/messages/send", to: "user_messages#send_message", as: "user_messages_send"
  post "users/messages/reply", to: "user_messages#reply_message", as: "user_messages_reply"

  get "/users/messages/search_messages", to: "user_messages#search_messages"
  get "users/messages/show_message", to: "user_messages#show_message"
  get "users/messages/newest_sort", to: "user_messages#newest_sort"
  put "users/messages/move_to_trash", to: "user_messages#move_to_trash"
  put "users/messages/mark_all_as_read", to: "user_messages#mark_all_read"
  put "users/messages/mark_all_as_unread", to: "user_messages#mark_all_unread"
  put "users/messages/delete_convos", to: "user_messages#delete_convos"
  put "users/messages/untrash_convos", to: "user_messages#untrash_convos"





  get 'users/notifications/long_pull', to: "user_notifications#long_pull_check"
  get 'users/notifications/update_notifications', to: 'user_notifications#update_dropdowns'
  patch "users/notifications/mark_read", to: "user_notifications#mark_as_read"


  # Friend Request

  get "pending_friends/requests", to: 'pending_friends#index', as: 'requests'
  get "pending_friends/requests/sort", to: 'pending_friends#sort'
  post "pending_friends/create", to: 'pending_friends#create'
  post "pending_friends/accept", to: "pending_friends#accept"
  post "pending_friends/ignore", to: "pending_friends#ignore"

  # Friends

  get "users/friends/search", to: "friends#search"
  post 'users/friends/invite', to: 'friends#invite'
  get 'users/:prid/friends', to: 'friends#index', as: 'friends'
  delete 'users/friends/delete', to: 'friends#delete'


  get 'dashboards/online_poker_room', to: 'dashboards#online_poker_room', as: 'dash_online_poker'
  get 'dashboards/online_poker_room/edit', to: 'dashboards#online_poker_room_edit', as: 'dash_online_poker_edit'
  get 'dashboards/casino_poker_room', to: 'dashboards#casino_poker_room', as: 'dash_casino_poker'
  get 'dashboards/casino_poker_room/edit', to: 'dashboards#casino_poker_room_edit', as: 'dash_casino_poker_edit'
  get 'dashboards/life_time', to: 'dashboards#life_time', as: 'dash_life_time'
  get 'dashboards/charts', to: 'dashboards#charts', as: 'dash_charts'
  post "dashboards/online_poker_room/edit", to: 'dashboards#online_edit'
  post "dashboards/casino_poker_room/edit", to: 'dashboards#casino_edit'
  post "dashboards/tournament_log_edit", to: 'dashboards#tournament_log_edit'
  post "dashboards/cash_log_edit", to: 'dashboards#cash_log_edit'
  post "/dashboards/highlight_best_hand", to: 'dashboards#highlight_best_hand'
  get 'dashboards/online_tournament_edit_form', to: 'dashboards#online_tournament_edit_form'
  delete 'dashboards/tournament_log_delete', to: 'dashboards#tournament_log_delete'
  get 'dashboards/online_cash_edit_form', to: 'dashboards#online_cash_edit_form'
  delete 'dashboards/cash_log_delete', to: 'dashboards#cash_log_delete'
  post "webhook/receiver", to: 'webhook#receiver'

  

   
  get "sign_in", to: "user_sessions#new"
  post "user_sessions", to:"user_sessions#create"
  delete "user_sessions", to: "user_sessions#destroy"

  post "activity_likes/create"
  post "activity_comments/create"

  get "errors/error_500"
  get "errors/error_404"

  post "user_locations/update"

  post "user_youtubes/create_or_update"
  post "user_facebooks/create_or_update"
  post "user_twitters/create_or_update"
  post "user_instagrams/create_or_update"

  patch "user_youtubes/create_or_update"
  patch "user_facebooks/create_or_update"
  patch "user_twitters/create_or_update"  
  patch "user_instagrams/create_or_update"

  get "forums/section/:id", to: "forums#section"
  get "forums/thread/:id", to: "forums#thread"
  get "forum/index", to: "forums#index", as: 'forum'
  get "forums/thread/:id/post/new", to: "forums#new_post"
  post "forums/create_post", to: "forums#create_post"
  get "forums/thread/:id/new",to: "forums#new_thread"
  post "forums/create_thread"
  get "forums/search_thread"
  get "forums/search_threads"
  resources :contact_forms

end

app/models/pending_friend.rb
# == Schema Information
#
# Table name: pending_friends
#
#  id               :integer          not null, primary key
#  requester_id     :integer
#  requestee_id     :integer
#  how_you_know_him :string(255)
#  message          :text
#  created_at       :datetime
#  updated_at       :datetime
#

class PendingFriend < ActiveRecord::Base
  belongs_to :requester, foreign_key: "requester_id", class_name: "User"
  belongs_to :requestee, foreign_key: "requestee_id", class_name: "User"


  validates_uniqueness_of :requestee_id, :scope => :requester_id



  after_create :send_notification


  class << self
    def friend_requests_for_user user
      where('requestee_id = ?', user.id).includes(:requestee).includes(:requestee => :user_profile_picture).includes(:requestee => :user_location).to_a.reverse
    end
  end

  def send_notification
    self.requestee.notify('new_friend_request', 'friend', @pending_friend)
  end

  def accept!
    Friend.create_friendship(self.requester, self.requestee)
    self.destroy
  end

  def ignore!
    DeniedFriend.create_denied_friendship(self.requester, self.requestee)
    self.destroy
  end
end

app/controllers/pending_friends_controller.rb
class PendingFriendsController < ApplicationController
  before_action :find_request, only: [:accept, :ignore]
  before_action :redirect_non_signed_in_user


  def index
    @data = UserProfile.get(current_user.prid, current_user)
    @requests = PendingFriend.friend_requests_for_user(current_user)
    @requests += DeniedFriend.denied_requests_for_user(current_user)
  
     @requests = @requests.paginate(:page => params[:page], :per_page => 11)
    @unread_friend_notifications.each {|n| n.mark_as_read(current_user)}
  end

  def create
    requestee = User.find(params[:pending_friend][:requestee_id])
    if current_user.opt_in == true
      ContactRequestMailer.send_connect_request(params[:pending_friend][:requester_id], params[:pending_friend][:requestee_id],params[:pending_friend][:how_you_know_him],params[:pending_friend][:message])
    end
    @pending_friend = PendingFriend.create(pending_friend_params)
    respond_to  do |format|
      format.js { render json: {}, status: :ok }
      format.json { render json: {}, status: :created }
    end
  end


  def sort
    requests = PendingFriend.friend_requests_for_user(current_user)
    requests.reverse! if params[:sort] == 'oldest'
    render :json => render_to_string( partial: '/pending_friends/pending_friend_requests', locals: { requests: requests } ).to_json, status: :ok
  end

  def accept
    
    if !@requests.blank?
      @requests.each {|r| r.accept!}
      @friends = User.friends_of_user(current_user).each_slice(20).to_a.flatten!
     render json: { partial:  render_to_string( :partial => '/contacts/contacts_results', :locals => { :friends => @friends,:profile_view=> false }) ,type: "accept"}.to_json, status: :ok

    else
       @denied_requests.each {|r| r.accept!}
       render :json => {}, :status => :ok
    end
  end

  def ignore
    if ! @requests.blank?
      @requests.each {|r| r.ignore!}
     else
       @denied_requests.each {|r| r.ignore!}
    end
    render :json => {}, :status => :ok
  end



  private
    def pending_friend_params
      params.require(:pending_friend).permit(:message, :requester_id, :requestee_id, :how_you_know_him)
    end

    def find_request
      @requests = PendingFriend.find_all_by_id(params[:reqIds])
      if @requests.blank?
        @denied_requests = DeniedFriend.find_all_by_id(params[:reqIds])
      end
    end

end

app/views/pending_friends/_friend_request_li.html.slim
.request_container
  / # p.time_ago = time_ago_in_words(conversation.last_message.created_at) + ' ago'
  .profile_picture
    = create_profile_pic(pending_friend.requester, 80)

  .requester_name
      - if !pending_friend.requester.blank? && !pending_friend.requester.name.blank?
        = link_to pending_friend.requester.name, profile_path(pending_friend.requester.prid)

  .action_buttons
    = link_to 'Connect', '#', :class => 'btn btn-success friend_action connect_button', :data => { request_id: pending_friend.id, type: 'accept'}
    = link_to 'Ignore', '#', :class => 'btn btn-gray friend_action', :data => { request_id: pending_friend.id, type: 'ignore'}

  br style="clear: left;"

app/views/pending_friends/_friend_requests_container.html.slim
- if @pending_friends.blank?
  div.no_requests_container
    p No New Requests

- else

  - @pending_friends.reverse.each do |pending_friend|
    li.connection_request_li
      = render "/pending_friends/friend_request_li", :pending_friend => pending_friend

div.see_all
  a.see_all_link href="/pending_friends/requests"
   p See All

app/views/pending_friends/_friend_requests_dropdown.html.slim
.dropdown
  = link_to "#", :id => "nav_friends", :class => "dropdown-toggle notify_icon", 'data-toggle' => "dropdown", data: {:not_type => 'friend'}  do
    i.icon-2x.icon-user.fa.fa-user

    - if !@unread_friend_notifications.blank? 
      span.notification_badge#request_badge
        = @unread_friend_notifications.count
    - else
      span.notification_badge#request_badge style="display:none;"


  ul.dropdown-menu#friend_drop.pull-right.col-md-5 role="menu"
    div#dropdown-title CONNECTION REQUESTS
    div.requests data-need-update="false"
      = render "/pending_friends/friend_requests_container", :pending_friends => @pending_friends

app/views/pending_friends/_pending_friend_requests.html.slim
- if !requests.empty?
  - requests.each do |request|
    div.request_container
      div.check_box
        = check_box_tag :marked, nil, nil, class: "regular-checkbox", data: {request_id: request.id}

      div.picture_box
        = create_profile_pic(request.requester, 80)


      div.right_section
        - if !request.requester.blank? && !request.requester.name.blank?
          span.name = request.requester.name
        span.request_buttons
          = link_to 'Accept', '#', :class => 'btn btn-success friend_action', :data => { request_id: request.id, type: 'accept'}
          

      br style="clear: left;"
  = will_paginate requests
- else
  div.request_container
    p style="text-align:center;" No Requests

app/views/pending_friends/_pending_friends_modal.html.slim
div.modal.fade#friend-request tabindex="-1" role="dialog" aria-hidden="true"
  div.modal-dialog
    div.modal-content
      div.modal-body#friend_request_modal_body
        button.close type="button" data-dismiss="modal" aria-hidden="true" &times;

        center
          h2 = "Request #{@data[:user].name} to Connect"
        br
        div.row
          = form_for @data[:pending_friend], url: { action: "create", controller: "pending_friends" }, html: { id: 'friend_request_form'  }, remote:true do |pending_friend_form|
            = pending_friend_form.hidden_field :requester_id, value: current_user.id
            = pending_friend_form.hidden_field :requestee_id, value: @data[:user].id
            div.col-md-5.marleft4per
              div.marbott15px How do you know #{@data[:user].name.split(" ")[0]}?

              div.form-group#pending_friends_form
                = pending_friend_form.radio_button :how_you_know_him, "Online Poker Room", style: "margin-right:4px;"
                = label :how_you_know_him, "Online Poker Room", value: "Online Poker Room"

              div.form-group#pending_friends_form
                = pending_friend_form.radio_button :how_you_know_him, "Online Casino Room", style: "margin-right:4px;"
                = label :how_you_know_him, "Online Casino Room", value: "Online Casino Room"

              div.form-group#pending_friends_form
                = pending_friend_form.radio_button :how_you_know_him, "Friend", style: "margin-right:4px;"
                = label :how_you_know_him, "Friend", value: "Friend"

              div.form-group#pending_friends_form
                = pending_friend_form.radio_button :how_you_know_him, "Other", style: "margin-right:4px;"
                = label :how_you_know_him, "Other", value: "Other"
              div.form-group#pending_friends_form
                = pending_friend_form.radio_button :how_you_know_him, "I don't know #{@data[:user].name}", style: "margin-right:4px;"
                = label :how_you_know_him, "I don't know "+ "#{@data[:user].name.split(" ")[0]}", class: "inline_label", value: "I don't know #{@data[:user].name}"



            div.col-md-6
              div Include a personal message: <span id='pending_friend_greyFont'>(optional)</span>
              br
              = pending_friend_form.text_area :message, size: "37x5", class: "form-control", placeholder: "I'd like to add you to my poker network."
              br
              center
                button.btn.btn-success SEND REQUEST

app/views/pending_friends/index.html.slim
div.row
  div#main_section.box.messages_page_container
    div.row#message_nav_and_all_container
      div#message_nav_container
        div.search_field_container
          = text_field_tag :message_search, nil, placeholder: "Search", id: 'message_search_field'
          a#search_messages.search_inbox_icon href="#" data-type="inbox"
            span.glyphicon.glyphicon-search

        div#message_nav_ul_container
          ul.message_nav_ul
            li.message_nav_li
              = link_to "Inbox", user_messages_path
            li.message_nav_li
              =link_to "Sent", user_messages_sent_path

            li.message_nav_li
              = link_to "Trash", user_messages_trash_path



      div#messages_container
        div.messages_invitation_container
          ul.messages_invitation
            li = link_to "MESSAGES", user_messages_path

            li = link_to "REQUESTS", requests_path, class: 'active'

        div.message_actions_container
          ul.message_actions_list
            li = link_to 'ACCEPT', '#', class: 'request_action_listener', data: {action: 'accept'}
            li = link_to 'IGNORE', '#', class: 'request_action_listener', data: {action: 'ignore'}

          ul.message_sort_list
            li.select
              span
                | Select:
                = link_to ' All ', '#', id: "select_all"
                span |
                = link_to " None", "#", id: 'deselect_all'

            li.select
              span.action
                | Action

        div.requests_list_container
          = render '/pending_friends/pending_friend_requests', requests: @requests


  div#sidebar.box.sidebar
    = render "sidebars/profile_side_bar", user: current_user